### ISSUE TITLE
Use GitHub Actions for notifications

### ISSUE THREAD

**Issue by dhimmel** [dhimmel/hackjohn#6]
It should be possible to do everything via GitHub actions, so users don't have to run anything locally.

Instead, a user would fork `dhimmel/hackjohn` and edit the parameters. Then scheduled cron actions would take care of the rest.

**Comment by dhimmel** [comment]
One option is to use a GitHub Issues thread for notifications. Some code in case someone wants to develop the idea further:

```yaml
    - name: Issue Comment
      uses: actions/github-script@v1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.search.issuesAndPullRequests({
            q: '"Hackjohn Notifications Thread" in:title'
          })
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'insert hackjohn output here'
          })
```
